name: flutter_showcases

packages:
  - packages/**

scripts:
  run:deeplink_and_push_notification:
    run: melos exec -- flutter run --flavor staging
    select-package:
      scope: 'deeplink_and_push_notification'

  run:responsive_ui:
    run: melos exec -- flutter run
    select-package:
      scope: 'responsive_ui'
